Resources:  
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-00c39f71452c08778"
      KeyName: "testkey"
      BlockDeviceMappings: 
      - DeviceName: "/dev/sdm"
        Ebs: 
          VolumeType: "io1"
          Iops: "200"
          VolumeSize: "20"
      - DeviceName: "/dev/sdk"
        NoDevice: {}
